# Generated by Django 6.0.3 on 2026-05-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfpaced', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionjob',
            name='file_content',
            field=models.BinaryField(blank=True),
        ),
    ]
