# Generated by Django 6.0.3 on 2026-05-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfpaced', '0013_monitored_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='health_status',
            field=models.CharField(choices=[('graduated', 'Graduated'), ('dormant', 'Dormant'), ('at_risk', 'At Risk'), ('active', 'Active'), ('not_yet_started', 'Not Yet Started')], db_index=True, default='not_yet_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='learner',
            name='first_seen_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='overall_health_status',
            field=models.CharField(choices=[('graduated', 'Graduated'), ('dormant', 'Dormant'), ('at_risk', 'At Risk'), ('active', 'Active'), ('not_yet_started', 'Not Yet Started')], db_index=True, default='not_yet_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='learner',
            name='payment_status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('due_soon', 'Due Soon'), ('grace_period', 'Grace Period'), ('overdue', 'Overdue'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='programme',
            name='awards_credentials',
            field=models.BooleanField(default=True, help_text='Uncheck for programmes that do not award course-completion badges.'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='is_prerequisite',
            field=models.BooleanField(db_index=True, default=False, help_text="Mark for onboarding/prerequisite programmes (e.g. WALX) that run before a learner's substantive enrolment. Excluded from headline metrics and health rollups."),
        ),
    ]
