# Generated by Django 6.0.3 on 2026-05-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfpaced', '0015_pod_import_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='enrolmentsnapshot',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('due_soon', 'Due Soon'), ('grace_period', 'Grace Period'), ('overdue', 'Overdue'), ('unknown', 'Unpaid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learner',
            name='payment_status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('due_soon', 'Due Soon'), ('grace_period', 'Grace Period'), ('overdue', 'Overdue'), ('unknown', 'Unpaid')], db_index=True, default='unknown', max_length=20),
        ),
    ]
