# Generated by Django 6.0.3 on 2026-05-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfpaced', '0016_learner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmenamemapping',
            name='csv_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
