# Generated by Django 6.0.3 on 2026-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfpaced', '0024_backfill_has_activity_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionjob',
            name='data_as_of_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
